### ISSUE TITLE
Functions API requirement?

### ISSUE THREAD

**Issue by teppokoivula** [BernhardBaumrock/RockFinder2#7]
While testing RockFinder2 out, I noticed that it currently requires enabling the Functions API. Based on a cursory glance it seems that this might actually only be required for a single modules() call in ProcessRockFinder2.module.php.

If this is really the only instance where the Functions API is required, would you be willing to consider changing it? I'll readily admit that this is a personal preference, but I don't usually enable the Functions API unless absolutely necessary :)

**Comment by flydev-fr** [comment]
Same here https://github.com/BernhardBaumrock/RockFinder2/issues/8

**Comment by teppokoivula** [comment]
@BernhardBaumrock, not sure if you noticed this – just a quick heads-up, no panic though :)

**Comment by BernhardBaumrock** [comment]
Thx @teppokoivula and @flydev-fr ! Just pushed a fix (and indeed again missed that issue - now I'm watching the repo).
