### ISSUE TITLE
Mixed case field names result in SQL error.

### ISSUE THREAD

**Issue by kiwigringo** [BernhardBaumrock/RockFinder2#9]
Example of problem:
```
$rf->addColumns([
  'title', // default pw field + alias
  'stockCode', // This triggers an SQL error.
]);
```

Cause: Processwire allows field names with mixed case, but mySQL stores table names in lower case.

Suggested Fix: in function addColumnTypes replace all instances of this line:
`$table = $this->getTable($data->column);`
with
`$table = strtolower($this->getTable($data->column));`

Also required in join function.

Tested, and appears to work in sandbox.

**Comment by BernhardBaumrock** [comment]
Hey @kiwigringo thx for the report!

I've just tried mixed case fields and the work as expected:
![img](https://i.imgur.com/fidz0ww.png)

See https://github.com/BernhardBaumrock/tabulator.test/commit/50db1a4d4c8fdf5ccb7f45d7b6c4bf6482fd8bec

Could you try installing the tabulator.test repo and check wheter it also works for you or not?
